// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_libtransmission.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterLibtransmissionBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterLibtransmissionBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterLibtransmissionBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Initialize a transmission session given a config dir and an app name.
  void init_session(
    ffi.Pointer<ffi.Char> config_dir,
  ) {
    return _init_session(
      config_dir,
    );
  }

  late final _init_sessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'init_session');
  late final _init_session =
      _init_sessionPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Close transmission session.
  void close_session() {
    return _close_session();
  }

  late final _close_sessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('close_session');
  late final _close_session = _close_sessionPtr.asFunction<void Function()>();

  /// Submit a request and return immediately. The response is delivered through
  /// cb, tagged with request_id.
  void request_async(
    int request_id,
    ffi.Pointer<ffi.Char> json_string,
    response_callback cb,
  ) {
    return _request_async(
      request_id,
      json_string,
      cb,
    );
  }

  late final _request_asyncPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>,
              response_callback)>>('request_async');
  late final _request_async = _request_asyncPtr.asFunction<
      void Function(int, ffi.Pointer<ffi.Char>, response_callback)>();

  /// Release a buffer handed to a response_callback.
  void free_response(
    ffi.Pointer<ffi.Char> json,
  ) {
    return _free_response(
      json,
    );
  }

  late final _free_responsePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'free_response');
  late final _free_response =
      _free_responsePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Save current transmission settings to disk.
  void save_settings() {
    return _save_settings();
  }

  late final _save_settingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('save_settings');
  late final _save_settings = _save_settingsPtr.asFunction<void Function()>();

  /// Reset all session settings
  void reset_settings() {
    return _reset_settings();
  }

  late final _reset_settingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('reset_settings');
  late final _reset_settings = _reset_settingsPtr.asFunction<void Function()>();
}

/// Invoked when a request completes, possibly from another thread.
/// The json buffer must be released with free_response().
typedef response_callback
    = ffi.Pointer<ffi.NativeFunction<response_callbackFunction>>;
typedef response_callbackFunction = ffi.Void Function(
    ffi.Int64 request_id, ffi.Pointer<ffi.Char> json);
typedef Dartresponse_callbackFunction = void Function(
    int request_id, ffi.Pointer<ffi.Char> json);
